### ISSUE TITLE
MoodeAudio

### ISSUE THREAD

**Issue by gabmartini** [thibmaek/awesome-raspberry-pi#153]
Hi! The MoodeAudio project is awesome, I think that it deserves a place in this list, don't you think? 😄  https://moodeaudio.org/

**Comment by thibmaek** [comment]
Any benefits over Volumio/Rune Audio?

Regardless, feel free to add this via a PR to the list. The details on how to add it are outlined in [CONTRIBUTING.md](https://github.com/thibmaek/awesome-raspberry-pi/blob/master/CONTRIBUTING.md)

Closing this issue, since the response is simply: sure, create a PR and I'll merge it. Issues are not the place to discuss this, I mainly go through PR review :)
